apiVersion: v1
kind: Service
metadata:
  name: homework-svc
  labels:
    app: homework
    ver: v1
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
  selector:
    app: homework
    ver: v1     
